# all packages needed for scripts
library(tidyverse)
library(maps)
library(ggthemes)
library(ggpubr)
library(ggrepel)
library(plotly)
library(rphylopic)
library(png)
library(cowplot)
library(cartography)
library(sf)
library(data.table)
library(janitor)
